### ISSUE TITLE
Error: unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by niraj602** [AndroBugs/AndroBugs_Framework#20]
Hi There,

While executing the command androbugs.exe -f [APK file], I am getting below error.

Traceback (most recent call last):
  File "androbugs.py", line 3573, in main
  File "androbugs.py", line 1059, in __analyze
  File "tools\modified\androguard\core\bytecodes\apk.py", line 189, in __init__
  File "C:\Python27\lib\zipfile.py", line 766, in __init__
    x._decodeExtra()
  File "C:\Python27\lib\zipfile.py", line 853, in _RealGetContents
    zef_file.seek(zinfo.header_offset, 0)
  File "C:\Python27\lib\zipfile.py", line 388, in _decodeExtra

error: unpack requires a string argument of length 4

Is there any fix for this?

Thanks!

**Comment by AndroBugs** [comment]
AndroBugs uses Androguard as a decompiler.
It should be the issue in [Androguard](https://github.com/androguard/androguard).

**Comment by AndroBugs** [comment]
@niraj602 Could you provide the APK to me?
I may have a workaround that can solve this kind of issue.

**Comment by ricky3pm** [comment]
Hi I tried upgrading Python to 2.7.16 with the same result

**Comment by ZAIRAWASIM** [comment]
Thanks bro but what is the use of this framework is it related to hacking
android
