### ISSUE TITLE
Error when executing in line 844 in "apk.py" file

### ISSUE THREAD

**Issue by sreenureddy63** [AndroBugs/AndroBugs_Framework#31]
C:\Mobile tools\AndroBugs_Framework>androbugs.py
Traceback (most recent call last):
  File "C:\Mobile tools\AndroBugs_Framework\androbugs.py", line 4, in <module>
    from tools.modified.androguard.core.bytecodes import apk
  File "C:\Mobile tools\AndroBugs_Framework\tools\modified\androguard\core\bytecodes\apk.py", line 884
    print "FILES: "
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("FILES: ")?

**Comment by AndroBugs** [comment]
AndroBugs Framework currently does not support Python 3.X.
Please use Python >= 2.7.16.

**Comment by sreenureddy63** [comment]
Thank you will try.



Thanks,
Sreeni


-------- Original message --------
