### ISSUE TITLE
Not Runing -  AttributeError

### ISSUE THREAD

**Issue by 0x-MRNOBODY-x0** [AndroBugs/AndroBugs_Framework#32]
I'm working with termux. When I run it, it shows an error like this ,

MR.N0B0DY_@android:~$ python2 androbugs.py -f test.apk -o res1.txt
*************************************************************************
**   AndroBugs Framework - Android App Security Vulnerability Scanner  **
**                            version: 1.0.0                           **
**     author: Yu-Cheng Lin (@AndroBugs, http://www.AndroBugs.com)     **
**               contact: androbugs.framework@gmail.com                **
*************************************************************************
Traceback (most recent call last):
  File "androbugs.py", line 3576, in main
    __analyze(writer, args)
  File "androbugs.py", line 1062, in __analyze
    a = apk.APK(apk_Path)
  File "/data/data/com.termux/files/home/AndroBugs_Framework/tools/modified/androguard/core/bytecodes/apk.py", line 230, in __init__
    self.permission_module = androconf.load_api_specific_resource_module("aosp_permissions", self.get_target_sdk_version())
  File "/data/data/com.termux/files/home/AndroBugs_Framework/tools/modified/androguard/core/bytecodes/apk.py", line 764, in get_target_sdk_version
    return self.get_element( "uses-sdk", "targetSdkVersion" )
  File "/data/data/com.termux/files/home/AndroBugs_Framework/tools/modified/androguard/core/bytecodes/apk.py", line 558, in get_element
    for item in self.xml[i].getElementsByTagName(tag_name):
AttributeError: 'NoneType' object has no attribute 'getElementsByTagName'
MR.N0B0DY_@android:~$

Please tell me what I need to do ?

**Comment by sojhal** [comment]
I am facing the same issue. Did you find a solution @0x-MRNOBODY-x0  @AndroBugs ?

**Comment by AndroBugs** [comment]
Could you provide the APK file?

**Comment by Jawad-Saqib** [comment]
I'm also facing the same issue

**Comment by kemrec** [comment]
i am also experiencing same this issue? but seems to no one to here...

**Comment by liruishaer** [comment]
> Could you provide the APK file?
[Uploading 5_wit.android.bcpBankingApp.millenniumPL_2020-10-04.apk…]()
