### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by omgamer** [AndroBugs/AndroBugs_Framework#38]
I'm getting an error when i run this command: 
`python androbugs.py [APK FILE]` and I've also pasted the apk in to the folder but still someone plz help

Error: 
`Traceback (most recent call last):
  File "/data/data/com.termux/files/home/AndroBugs_Framework/androbugs.py", line 4, in <module>
    from tools.modified.androguard.core.bytecodes import apk
  File "/data/data/com.termux/files/home/AndroBugs_Framework/tools/modified/androguard/core/bytecodes/apk.py", line 884
    print "FILES: "
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("FILES: ")?`

**Comment by densi97** [comment]
It looks like you are using python3. Androbugs is written in python2. That's why you get this error.
