### ISSUE TITLE
i think pymongo hasnot set right

### ISSUE THREAD

**Issue by mathoyus** [AndroBugs/AndroBugs_Framework#5]
root@ubuntu:/opt/bug# python AndroBugs_ReportByVectorKey.py -v WEBVIEW_RCE -l Critical -b 20160512 -t lightsdk -a
## AndroBugs Framework: Android APK Vulnerability Reporter by Vector Name ##

Vector: WEBVIEW_RCE
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "AndroBugs_ReportByVectorKey.py", line 122, in <module>
    for report in query_result :
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1090, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 1012, in _refresh
    self.__read_concern))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/cursor.py", line 850, in __send_message
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 781, in _send_message_with_response
    server = topology.select_server(selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 142, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 118, in select_servers
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

root@ubuntu:/opt/bug# cat androbugs-db.cfg
[DB_Config]
MongoDB_Hostname: localhost             ;Change to your MongoDB's host name
MongoDB_Port: 27017                 ;Change to your MongoDB's port number
MongoDB_Database: AndroBugs_DBs         ;Your MongoDB database's name for AndroBugs

[DB_Collections]
Collection_Analyze_Result: AppInfos
Collection_Analyze_Success_Results: AnalyzeSuccessResults
Collection_Analyze_Success_Results_FastSearch: AnalyzeSuccessResultsFastSearch
Collection_Analyze_Fail_Results: AnalyzeExceptions

PS:can you read chinese

**Comment by AndroBugs** [comment]
Please check your MongoDB connection!
Google "MongoDB" will help!
